// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GenConfig(arg1:{[key: string]: string}):Promise<string>;

export function LoadConfigCache():Promise<any>;

export function LoadConfigTemplate():Promise<any>;

export function SaveConfig(arg1:string):Promise<string>;

export function SyncCsv():Promise<string>;
