// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GenConfig(arg1:{[key: string]: string}):Promise<main.Response>;

export function LoadConfigCache():Promise<main.Response>;

export function LoadConfigTemplate():Promise<main.Response>;

export function LoadProto():Promise<main.Response>;

export function SaveConfig(arg1:string):Promise<main.Response>;

export function SyncCsv():Promise<main.Response>;
