// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GenConfig(arg1) {
  return window['go']['main']['App']['GenConfig'](arg1);
}

export function LoadConfigCache() {
  return window['go']['main']['App']['LoadConfigCache']();
}

export function LoadProto() {
  return window['go']['main']['App']['LoadProto']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SyncData() {
  return window['go']['main']['App']['SyncData']();
}
