// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SyncCsv():void;

export function GenerateConfig(arg1:string):void;

export function Greet():Promise<string>;

export function LoadConfig():Promise<any>;

export function SaveConfig(arg1:any):void;
